
version: '3.8'

volumes:
  dbVolume:
  prometheus:
  loki:
  tempo:
  grafana-data:

services:

  derp-testing:
    container_name: derptestContainer
    build: 
        context: ..
        dockerfile: ./TheTesting/Test.Dockerfile
    command: tail -f /dev/null
  
  postgres:
    container_name: test-my_postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      -  dbVolume:/var/lib/postgresql/data
    ports:
      - "5437:5432"




  

  