
version: '3.8'

networks:
  my-network:
      driver: bridge

volumes:
  dbVolume:
services:
  postgres:
    container_name: my_postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      -  dbVolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  thederpeningapiimage:
    container_name: "thederpeningapiimage"
    build:
        context: ..
        dockerfile: ./TheDerpeningAPI/Dockerfile
    ports:
        - "7568:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7568/health"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - my-network
  
  thederpeningimage:
    container_name: "thederpeningimage"
    build:
        context: ..
        dockerfile: ./TheDerpening/Dockerfile
    ports:
        - "7564:8080"
    networks:
        - my-network




  

  