
version: '3.8'

services:
  postgres:
    container_name: my_postgres_db
    image: postgres:latest
    environment:
      - POSTGRES_USER=myusername
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=mydatabase
      - POSTGRES_INITDB_ARGS=--encoding=UTF-8 --lc-collate=C --lc-ctype=C
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      -  ./dbVolume:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  thederpeningimage:
    container_name: "thederpeningimage"
    build:
        context: ..
        dockerfile: ./TheDerpening/Dockerfile
    ports:
        - "7564:80"

  thederpeningapiimage:
    container_name: "thederpeningapiimage"
    build:
        context: ..
        dockerfile: ./DerpeningAPI/Dockerfile
    ports:
        - "7568:80"

  

  