name: backup database
on:
    - workflow_dispatch
jobs:
    backup:
        runs-on: self-hosted
        steps:
            - name: backup
              run: |
                CONTAINER_NAME = $(kubectl -n riley get pods --no-headers -o custom-columns=":metadata.name" | grep "thederpening-db-deployment")
                kubectl -n riley exec -t $CONTAINER_NAME -- \
                    pg_dumpall -c -U riley-user \
                    > /home/riley/dump.sql