name: DerpeningProject
run-name: Derp is derping
on:
  push:
  workflow_dispatch:

jobs:
  Deployment:
    runs-on: self-hosted
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 8.0.102

      - name: Set up unit and integrated Tests
        run: |
          cd TheTesting
          docker-compose up -d --build
          sleep 5
          docker-compose exec -T derp-testing dotnet test
      
      - name: Clean up Tests
        if: always()
        run: |
          cd TheTesting
          docker-compose down --remove-orphans --volumes

      - name: Check Warnings
        run: |
          dotnet build --warnaserror

      - name: Formatting Ensured
        run: dotnet format --verify-no-changes --verbosity diagnostic 

      - name: Getting Production Ready
        run: |
          cd TheDerpening
          docker-compose down --remove-orphans
          docker-compose up -d --build
      
      # - name: Kube
      #   run: |
      #     docker build -t 144.17.92.12:5000/riley/blazor-web:1
      #     docker push 144.17.92.12:5000/riley/blazor-web:1
      #     cd thederpening
      #     kubectl -n riley create configmap blazor-web-postgres-init --from-file=init.sql
      #     kubectl apply -f kube/

      - name: Send MS Teams Notification
        if: ${{ failure() }}
        uses: jdcargile/ms-teams-notification@v1.4
        with:
          github-token: ${{ github.token }}
          ms-teams-webhook-uri: ${{ secrets.TEAMS_WEBHOOK_URL }}
          notification-summary: Oh No! A derp went wrong!!!
          notification-color: dc3545
        
